"""create orders and order_items

Revision ID: 1f19ae426a93
Revises:
Create Date: 2025-12-01 20:18:54.591768

"""


# revision identifiers, used by Alembic.
revision = '1f19ae426a93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
